parameters:
  cl_slack.api_client.class: CL\Slack\Transport\ApiClient
  cl_slack.payload_factory.class: CL\Slack\Util\PayloadFactory
  cl_slack.payload_registry.class: CL\Slack\Util\PayloadRegistry

services:
  cl_slack.api_client:
    class: %cl_slack.api_client.class%
    arguments:
      - %cl_slack.api_token%
      - @jms_serializer.serializer

  cl_slack.payload_factory:
    class: %cl_slack.payload_factory.class%

  cl_slack.payload_registry:
    class: %cl_slack.payload_registry.class%
